### ISSUE TITLE
Support multiple routes

### ISSUE THREAD

**Issue by elgohr** [elgohr/cf-jetbrains-license-server#1]
At the moment the license server just takes the first route it can find on Cloudfoundry (https://github.com/elgohr/cf-jetbrains-license-server/blob/master/entrypoint.sh#L4) and configures a virtualHost in jetty (https://github.com/elgohr/cf-jetbrains-license-server/blob/master/entrypoint.sh#L9).
As the option says virtualHost**s**, it might be possible to have multiple routes.

**Comment by elgohr** [comment]
As said on https://www.jetbrains.com/help/license_server/passed_host_not_allowed.html
> If there are several hosts, please specify them separated with a comma.

**Comment by elgohr** [comment]
In theory this should already work. See
`export VCAP_APPLICATION='{"instance_id":"fe98dc76ba549876543210abcd1234","instance_index":0,"host":"0.0.0.0","port":61857,"started_at":"2013-08-1200:05:29 +0000","started_at_timestamp":1376265929,"start":"2013-08-1200:05:29+0000","state_timestamp":1376265929,"limits":{"mem":512,"disk":1024,"fds":16384},"application_version":"ab12cd34-5678-abcd-0123-abcdef987654","application_name":"styx-james","application_uris":["my-app.example.com","my-app.example1.com"],"version":"ab12cd34-5678-abcd-0123-abcdef987654","name":"my-app","uris":["my-app.example.com","my-app.example1.com"],"users":null}'
echo $(echo "$VCAP_APPLICATION" | cut -d'[' -f2 | cut -d']' -f1 | tr -d '"')
`

**Comment by elgohr** [comment]
The server starts up the right way. 
The registration process uses the same hostname variable, in this way it crashes (https://github.com/elgohr/cf-jetbrains-license-server/blob/master/register.sh#L9) as https://my-app.example.com,my-app.example1.com is no valid url.

**Comment by elgohr** [comment]
Added a trial version to https://github.com/elgohr/cf-jetbrains-license-server/tree/edge
Docker: lgohr/cf-jetbrains-license-server:edge

As this is breaking, I'm not that happy about it

**Comment by FlorianSW** [comment]
So the breaking change is only that a new env variable $SERVER_HOSTNAME needs to be set, right? So in order to maintain backwards-compatibility, we could "simply" check, if this variable is set, and if not, assign the value of $HOSTNAME to it, as this should, in deployments with the current version, be already only one domain (this could also be checked by throwing an error if the value contains a comma).

**Comment by FlorianSW** [comment]
See PR #2 for that (could probably be improved, though).

**Comment by tenjaa** [comment]
What about having unique credentials per route?
The easiest solution would be to just leave them empty and do it externally.

**Comment by FlorianSW** [comment]
The license server itself does not handle the credentials as far as I know. You would "just" bind routes to the app in CloudFoundry and bind another Router-Service to this route which checks the auth (like basic auth) before forwarding the request to the app. In this way, each route can have their own credentials.

**Comment by elgohr** [comment]
Correct, the credentials are used in the registration process to access the server via one of the routes.

**Comment by elgohr** [comment]
So there is a new version on the edge branch, which should be ok with multiple routes.
Now we would need an integration test...

**Comment by elgohr** [comment]
https://github.com/elgohr/cf-jetbrains-license-server/commit/716377a47087195aa7a34152846a4a5f229c613c
